###
GET https://envios-mym-api.vercel.app/guia

###
GET http://localhost:3001/api/guia/60510880ec7df4cc667c5930

###
GET http://localhost:3001/api/tracking

###
POST  http://localhost:3001/api/guia/Bodega%20Miami/605108bfec7df4cc667c5931
content-type: application/json


###
# POST  http://localhost:3001/api/cliente
# content-type: application/json

# {"cliente": 
#     {
#         "tipoid":"cc",
#         "numid":"",
#         "nombre":"pru",
#         "email":"pru@egecol.com",
#         "telefono":"123",
#         "pais":"Colombia",
#         "ciudad":"Bogota",
#         "direccion":"pru",
#         "unidad":"lb",
#         "vlrUnidad":{"$numberDouble":"3"},
#         "vlrSeguro":{"$numberDouble":"5.0"}
#     }
# }
